services:
  - type: web
    name: fund-manager
    env: node
    plan: free
    region: singapore
    buildCommand: "npm run render-build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    healthCheckPath: /api/settings
